"""add email and reset token fields to users

Revision ID: 83fbf6fded67
Revises: f68b422faa99
Create Date: 2026-08-18 11:49:51.318736

"""
import secrets
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83fbf6fded67'
down_revision: Union[str, Sequence[str], None] = 'f68b422faa99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_users = sa.table('users', sa.column('id', sa.Integer), sa.column('email', sa.String))


def upgrade() -> None:
    """Upgrade schema."""
    # Add as nullable first — existing rows have no email yet, so a straight
    # NOT NULL add would fail against a non-empty table. Backfill a unique
    # placeholder per row, then tighten the constraint. Placeholders use the
    # `.invalid` TLD (RFC 2606) so they're recognizably non-deliverable
    # rather than looking like a real, forgotten address.
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(), nullable=True))

    conn = op.get_bind()
    for user_id in conn.execute(sa.select(_users.c.id)).scalars():
        placeholder = f"user{user_id}-{secrets.token_hex(4)}@chessbook.invalid"
        conn.execute(_users.update().where(_users.c.id == user_id).values(email=placeholder))

    op.alter_column('users', 'email', nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
