"""initial schema

Revision ID: f68b422faa99
Revises: 
Create Date: 2026-08-17 20:26:51.821968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68b422faa99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frequency_cache',
    sa.Column('fen', sa.String(), nullable=False),
    sa.Column('ratings_key', sa.String(), nullable=False),
    sa.Column('speeds_key', sa.String(), nullable=False),
    sa.Column('moves', sa.JSON(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('fen', 'ratings_key', 'speeds_key')
    )
    op.create_table('games',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('white', sa.String(), nullable=True),
    sa.Column('black', sa.String(), nullable=True),
    sa.Column('white_rating', sa.Integer(), nullable=True),
    sa.Column('black_rating', sa.Integer(), nullable=True),
    sa.Column('is_white', sa.Boolean(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('my_result', sa.String(), nullable=True),
    sa.Column('opp_result', sa.String(), nullable=True),
    sa.Column('opening', sa.String(), nullable=True),
    sa.Column('moves', sa.JSON(), nullable=True),
    sa.Column('deviation', sa.JSON(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('time_control', sa.String(), nullable=True),
    sa.Column('time_class', sa.String(), nullable=True),
    sa.Column('rated', sa.Boolean(), nullable=True),
    sa.Column('accuracy', sa.JSON(), nullable=True),
    sa.Column('game_url', sa.String(), nullable=True),
    sa.Column('tournament', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_username'), 'games', ['username'], unique=False)
    op.create_table('openings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('chesscom_username', sa.String(), nullable=True),
    sa.Column('platform_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('endgame_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.String(), nullable=False),
    sa.Column('solved', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('solved_at', sa.DateTime(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('win_streak', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'puzzle_id', name='uq_user_endgame')
    )
    op.create_index(op.f('ix_endgame_progress_puzzle_id'), 'endgame_progress', ['puzzle_id'], unique=False)
    op.create_index(op.f('ix_endgame_progress_user_id'), 'endgame_progress', ['user_id'], unique=False)
    op.create_table('lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opening_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('moves', sa.JSON(), nullable=False),
    sa.Column('idea', sa.Text(), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('next_review', sa.Date(), nullable=True),
    sa.Column('retention', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['opening_id'], ['openings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.String(), nullable=False),
    sa.Column('solved', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('solved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'puzzle_id', name='uq_user_puzzle')
    )
    op.create_index(op.f('ix_problem_progress_puzzle_id'), 'problem_progress', ['puzzle_id'], unique=False)
    op.create_index(op.f('ix_problem_progress_user_id'), 'problem_progress', ['user_id'], unique=False)
    op.create_table('user_openings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opening_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['opening_id'], ['openings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opening_id', name='uq_user_opening')
    )
    op.create_index(op.f('ix_user_openings_opening_id'), 'user_openings', ['opening_id'], unique=False)
    op.create_index(op.f('ix_user_openings_user_id'), 'user_openings', ['user_id'], unique=False)
    op.create_table('line_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('next_review', sa.Date(), nullable=True),
    sa.Column('retention', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'line_id', name='uq_user_line_progress')
    )
    op.create_index(op.f('ix_line_progress_line_id'), 'line_progress', ['line_id'], unique=False)
    op.create_index(op.f('ix_line_progress_user_id'), 'line_progress', ['user_id'], unique=False)
    op.create_table('sparring_stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('ply_index', sa.Integer(), nullable=False),
    sa.Column('sparring_attempts', sa.Integer(), nullable=False),
    sa.Column('sparring_correct', sa.Integer(), nullable=False),
    sa.Column('last_sparring_result', sa.String(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'line_id', 'ply_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sparring_stats')
    op.drop_index(op.f('ix_line_progress_user_id'), table_name='line_progress')
    op.drop_index(op.f('ix_line_progress_line_id'), table_name='line_progress')
    op.drop_table('line_progress')
    op.drop_index(op.f('ix_user_openings_user_id'), table_name='user_openings')
    op.drop_index(op.f('ix_user_openings_opening_id'), table_name='user_openings')
    op.drop_table('user_openings')
    op.drop_index(op.f('ix_problem_progress_user_id'), table_name='problem_progress')
    op.drop_index(op.f('ix_problem_progress_puzzle_id'), table_name='problem_progress')
    op.drop_table('problem_progress')
    op.drop_table('lines')
    op.drop_index(op.f('ix_endgame_progress_user_id'), table_name='endgame_progress')
    op.drop_index(op.f('ix_endgame_progress_puzzle_id'), table_name='endgame_progress')
    op.drop_table('endgame_progress')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('openings')
    op.drop_index(op.f('ix_games_username'), table_name='games')
    op.drop_table('games')
    op.drop_table('frequency_cache')
    # ### end Alembic commands ###
